### ISSUE TITLE
Does the clock button work on local graphs? Permissions error

### ISSUE THREAD

**Issue by emmakat** [abhayprasanna/abhayprasanna.github.io#11]
Hi, 
I love the new clock button!~ I tried to use it also for my local graph but it gives an error "You do not have permission to view this database". Is that expected behavior? Does it not work on local graphs?

Thanks!

**Comment by abhayprasanna** [comment]
@emmakat Thanks for flagging this issue! For local graphs, please change line 39 to:

`let roamuri = "https://roamresearch.com/#/offline/";`

That should work!
