### ISSUE TITLE
Unexpected Border in mobile view

### ISSUE THREAD

**Issue by overfullstack** [abhayprasanna/abhayprasanna.github.io#12]
Thanks for this awesome theme. I see an unexpected and border on the right and bottom in mobile view. Able to reproduce it with "Toggle device emulation" on chrome. PFA the screenshot from Samsung Galaxy S20
![Screenshot_20210618-221328](https://user-images.githubusercontent.com/13434911/122659942-84e98f80-d19a-11eb-96c8-e8c41d2bee58.jpg)

**Comment by overfullstack** [comment]
This seems to be caused by Roam42 plugin. Disabling it has removed this border. However as the documentation of this theme says it works better with Raom42, this can be an issue to look into.

**Comment by abhayprasanna** [comment]
Interesting - does it also happen with my theme off and Roam42 on? Or with other themes?

**Comment by overfullstack** [comment]
It happens with your theme off as well.

**Comment by abhayprasanna** [comment]
@dvargas92495 thoughts?

**Comment by dvargasfuertes** [comment]
this is odd. I don't see roam42 css that could cause this and am not able to repro. @overfullstack if you have time this week for a call we could try to debug it together: https://calendly.com/dvargas92495/roamjs

**Comment by abhayprasanna** [comment]
This should be fixed now - please reopen if you face it again.
