### ISSUE TITLE
Only showing normal kaban table

### ISSUE THREAD

**Issue by brunoeducsantos** [abhayprasanna/abhayprasanna.github.io#13]
Hi, 
THanks for the amazing plugin.
For some reason it isn't showing the css agenda agenda , just the normal kaban table. 
May this have resulted from a roam research change?
![image](https://user-images.githubusercontent.com/3111976/133123723-6b027d6a-33fc-4fb0-838e-110aef6175d8.png)

Thanks ,
Bruno

**Comment by abhayprasanna** [comment]
Hi Bruno, 
Seems to be working fine on my end. Are you sure you have the kanban correctly indented under a block with [[Daily agenda]], and are you ensuring the import line for the CSS is on top of the roam/css page?

**Comment by brunoeducsantos** [comment]
Sorry for bothering. It is a problem with Desktop app. If I use the webapp it works. Thanks for your feedback!

**Comment by abhayprasanna** [comment]
> Sorry for bothering. It is a problem with Desktop app. If I use the webapp it works. Thanks for your feedback!

Interesting! It works fine for me in the desktop app. Let me know if you want to troubleshoot.
