### ISSUE TITLE
Code block not black even when in dark theme

### ISSUE THREAD

**Issue by angieloux** [abhayprasanna/abhayprasanna.github.io#15]
Hey there-- thanks so much for this amazing theme! I've been using Material palenight for ages.

For some reason the other day the code blocks changed to all white:
![Screen Shot 2021-11-15 at 10 42 44 am](https://user-images.githubusercontent.com/70993668/141703594-8ea6691e-aac3-40bc-9105-e98e3a03ca30.png)

I've disabled all other extensions/themes and tried it out on chrome vs desktop and can't seem to get it to go back to black as it was. A friend has tried on their Roam too. Unsure if it's an issue with a recent Roam update(?)

Any ideas on how to fix? 

Thanks! 

AJ

**Comment by abhayprasanna** [comment]
Fixed - refresh to update!

**Comment by angieloux** [comment]
Thank you!!
