### ISSUE TITLE
Auto tag feature request: support exclusion rule at a word level rather than a page

### ISSUE THREAD

**Issue by kkweon** [abhayprasanna/abhayprasanna.github.io#17]
### Current behavior

- We cannot exclude by a word so that some common words (e.g., done) are wrongly tagged since done is used by TODO mode. One has to exclude the page or turn off the auto tag mode momentarily.
 
### Expected behavior

- There should be a way to register a ignored word so that it doesn't get tagged automatically.

WDYT?

**Comment by mbernard** [comment]
I'm facing similar issues.

**Comment by abhayprasanna** [comment]
If you add DONE to the [[autotag-exclude]] page, it will not tag words like "done". Am I missing something?

**Comment by kkweon** [comment]
Hi, I got confused by this help description. Thanks, it works now.

> Exclusions: Create an [[autotag-exclude]] page. **Add pages you want to exclude** (i.e., not be autotagged), in a comma-spaced list without [[ ]], as the first block on that page.
