### ISSUE TITLE
Search bar not properly aligned when clicked on it.

### ISSUE THREAD

**Issue by orkhan10** [abhayprasanna/abhayprasanna.github.io#2]
![Screenshot 2021-01-25 at 01 14 59](https://user-images.githubusercontent.com/18570936/105648265-e555f880-5eaa-11eb-87d2-388254ccdb3b.png)

**Comment by abhayprasanna** [comment]
Hi @orkhan10, thanks for reporting these issues!

Will try to solve this - the trick I use to fix the topbar is leading to this issue. May require some creative solutions.

**Comment by abhayprasanna** [comment]
@orkhan10 One temporary fix - please add this code below the @import lines in your roam/css page and it will undo my topbar fixes in your graph and default to standard Roam behavior.

```
.roam-topbar {
  padding-right: 0px !important;
  width        : unset;
  position     : relative !important;
}

.roam-body-main {
  margin-top   : 0px;
}
```

**Comment by abhayprasanna** [comment]
I can't come up with a better fix than ^ so closing this - will revisit on next refactor to consider any alternative approaches.

**Comment by abhayprasanna** [comment]
@orkhan10 This is now fixed - the search bar will now show above the left sidebar unless the left sidebar is hovered over outside the search bar. Thanks to @GitMurf for the fix!

**Comment by orkhan10** [comment]
Thank you for maintaining! Love the theme.
