### ISSUE TITLE
Problem with the Mindmap plugin

### ISSUE THREAD

**Issue by orkhan10** [abhayprasanna/abhayprasanna.github.io#3]
https://twitter.com/dvargas92495/status/1350882265669259266?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1350905903713718273%7Ctwgr%5E%7Ctwcon%5Es3_&ref_url=https%3A%2F%2Fnote.com%2Fsangmin%2Fn%2Fn662c6e46063d

![Screenshot 2021-01-25 at 00 50 37](https://user-images.githubusercontent.com/18570936/105696935-334b1a80-5f04-11eb-9364-02aa3d36f45d.png)

**Comment by abhayprasanna** [comment]
@dvargas92495 Do you have any advice for how to ensure my theme doesn't mess with the mindmap CSS?

**Comment by dvargasfuertes** [comment]
This is the conflict: https://github.com/abhayprasanna/abhayprasanna.github.io/blob/master/better-dark-age.css#L687

what are we trying to target here?

**Comment by abhayprasanna** [comment]
Ah that's targeting {{[[diagram]]}} elements. I guess g rect { } is too broad a selector? Any thoughts on how to granulate separately for diagram without impacting the mindmap @dvargas92495 ?

**Comment by orkhan10** [comment]
@dvargas92495 
David you closed the other issue with the mind map. However, now there is another problem. I added the screenshots in the Issue. Just wanted to write here also, in case you don't get a notification as the issue is closed now.

**Comment by dvargasfuertes** [comment]
I still get notifications!

@abhayprasanna I think specifying as a child of `roam-body` will be sufficient. Mindmap portals out of the main react tree that diagrams will always render under

**Comment by abhayprasanna** [comment]
Thanks David - updated this accordingly and this should have fixed the issue.
