### ISSUE TITLE
Mindmap extension styling

### ISSUE THREAD

**Issue by orkhan10** [abhayprasanna/abhayprasanna.github.io#5]
Maybe not a lot of people use this extension and it is a bit buggy at the moment. However, I think that it will be very powerful if it gets fixed and that's why I think it maybe worth the extra additions to the theme. 

Edit: Thanks to David, the creator of the extension, the bug is now fixed. I have created also a new enhancement request for better image visibility in the Mindmap nodes.

`@media (prefers-color-scheme: dark) {
  #roamjs-mindmap-container {
	background: #292d3e !important;
	}
  .bp3-drawer-header {
    	background: #3b415c !important;  
	}
  .roamjs-mindmap-node {
    	color: #e8e6e3 !important;
  }
  .bp3-heading {
    	color: #e8e6e3 !important;
  }
}`

![before](https://user-images.githubusercontent.com/18570936/106964528-857d0e80-6742-11eb-8982-f6a56ac08769.png)

![after](https://user-images.githubusercontent.com/18570936/106964532-8877ff00-6742-11eb-9375-f2ca9b490612.png)

**Comment by orkhan10** [comment]
But I must be doing something wrong. because when I add the code above it cancels every css styling under it. 

![Screenshot 2021-02-04 at 23 49 41](https://user-images.githubusercontent.com/18570936/106965519-fa9d1380-6743-11eb-8adc-354306911e64.png)
![Screenshot 2021-02-04 at 23 49 34](https://user-images.githubusercontent.com/18570936/106965523-fcff6d80-6743-11eb-8150-2cc7c334fccc.png)

**Comment by abhayprasanna** [comment]
@orkhan10 Thank you! Can I consider this closed or would you like me to port this into the theme itself?

**Comment by orkhan10** [comment]
@abhayprasanna
It is your theme, you should do whatever you want. It is just a suggestion.

**Comment by orkhan10** [comment]
I think it would be wise to add it to theme, so that others can also benefit from it.
