### ISSUE TITLE
Smaller Left Sidebar 

### ISSUE THREAD

**Issue by orkhan10** [abhayprasanna/abhayprasanna.github.io#6]
When I work on my 13-inch mac on the go. I would like to maximize the screen real estate by making the left sidebar width smaller.

I did this with:
.roam-body .roam-app .roam-sidebar-container {
      width: 157px;
}

![YXEsOl7s](https://user-images.githubusercontent.com/18570936/107159933-72ad4880-6993-11eb-99f1-b374fc73a82d.jpg)

However, as you can see from the screenshot the main area contents did not move to the left even though the left sidebar is now smaller.

Do you maybe know what to edit to make this work?

Editing the following item in chrome inspector solves it, but I couldn't replicate this setting in roam/css.
<img width="1236" alt="Screenshot 2021-02-06 at 16 29 26" src="https://user-images.githubusercontent.com/18570936/107159871-0599b300-6993-11eb-913d-c93ba249602e.png">

**Comment by abhayprasanna** [comment]
Hi Orkhan - I tried a few things here, what do you think? https://roamresearch.com/#/app/roam-slack/page/HkG8srcq9

**Comment by orkhan10** [comment]
Oh, I love these!! Thank you soo much for taking the time to make these changes!

I just made the following changes so that roam42 deep nav shortcuts are more visible:

`.top-row,
.starred-pages-wrapper,
.page {
  font-size: 0.9em !important;
  padding: 8px 5px 8px 13px !important;
}
.log-button {
  font-size: 0.7em !important;
  padding: 8px 5px 8px 27px !important;
}`

![Screenshot 2021-02-16 at 22 34 29](https://user-images.githubusercontent.com/18570936/108124625-b6950180-70a7-11eb-8c67-6f394f778dbc.png)

This is so good I don't wanna close the issue in case others miss these config options. 😄 
You close it if you see fit. (Maybe put a link to this Issue in the description of the theme, so that others know that it is possible?)

**Comment by orkhan10** [comment]
I just noticed that the the sidebar stays like this when closed.
Do you think that it is possible to fix it? Or is it either this or default version.

For me personally it is small enough that it is not too much of an issue, would be nice though for notetaking (1/3 of screen roam 2/3 video).
And on mobile it is more problematic. 

![Screenshot 2021-02-16 at 22 48 05](https://user-images.githubusercontent.com/18570936/108125651-0cb67480-70a9-11eb-8fae-4d2e08db82f2.png)

**Comment by orkhan10** [comment]
I think it is not worth spending more time on this. I am closing the issue.
