### ISSUE TITLE
changing the highlighted working hours

### ISSUE THREAD

**Issue by BehroozBashokooh** [abhayprasanna/abhayprasanna.github.io#8]
Thank you very much for the daily agenda css, looks great. I tried to look into the code and see if the highlighted blue area of the working hours be changed (e.g to start from 7:00 to 16:00). can this be customized?

**Comment by abhayprasanna** [comment]
@BehroozBashokooh Hi sorry for the delay - yes they can be changed by updating the CSS code for that section. There is a comment in the CSS file explaining how to do this.
