### ISSUE TITLE
All the hours (duration) are not visible

### ISSUE THREAD

**Issue by drprincenanda** [abhayprasanna/abhayprasanna.github.io#9]
I can only see some of the duration's in the right bar

Can somebody help me on this?
![image](https://user-images.githubusercontent.com/82060934/113776374-262f8080-972a-11eb-8a7c-978e2c858676.png)

Thanks in advance.

**Comment by abhayprasanna** [comment]
Hi there - can you try scrolling down?

**Comment by drprincenanda** [comment]
Hi Abhay

thank you for looking into this for me. It works!

Apologies for being silly. I was not using mouse at that moment so could
not scroll properly.

Cheers!

Prince

**Comment by drprincenanda** [comment]
done
